version: '3'

services:
  # node:
  #   build:
  #     context: .
  #     dockerfile: ./docker/node/Dockerfile
  #   volumes:
  #     - .:/app
  #     - /app/node_modules
  #   ports:
  #     - 3000:3000
  #   command: npm run dev
  #   depends_on:
  #     - database
  #   environment:
  #     DATABASE_URL: postgresql://postgres:12341234@database:5432/postgres
  #
  database:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: 12341234
      POSTGRES_DB: postgres

networks:
  app-network:
